spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbs?serverTimezone=CST
    username: root
    password: root
  mvc:
    date-format: yyyy-MM-dd
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
